### ISSUE TITLE
what hardware equipment should i buy for using this plugin?

### ISSUE THREAD

**Issue by SilvesterLi** [amorenew/alps_rfid_n6737#13]
as the topic

**Comment by amorenew** [comment]
@SilvesterLi Sorry, I forgot about the issue
I recommend C72 https://github.com/amorenew/uhf_c72_plugin/issues/3

**Comment by amorenew** [comment]
@SilvesterLi When you want to buy a device be careful Chinese changes the c++ code a lot
so ask for SDK and check if the JNI folder is the same and same file sizes or not
https://github.com/amorenew/alps_rfid_n6737/tree/master/android/src/main/jniLibs/armeabi-v7a
