### ISSUE TITLE
Crashes upon load if installed from VS Code

### ISSUE THREAD

**Issue by bean5** [amorenew/alps_rfid_n6737#5]
**Expected**
Code builds and runs on ax6737 65n device.

**Actual**
* Code builds
* Code **does not** run -- crashes upon opening

**About My Device**
_Model Number_: ax6737_65_n
_Android version_: 7.0
_Kernel version_: 3.18.35
_Custom build version_: alps-mp-n0.mp1-V1.0.2_ax6737.65.n

There is no error message I can use to determine why it crashes.

**Comment by bean5** [comment]
@amorenew

**Comment by amorenew** [comment]
@bean5 Try to run without debugging mode
The library uses 32-bit .so files 
https://github.com/amorenew/alps_rfid_n6737/tree/master/android/src/main/jniLibs/armeabi-v7a
While running debug mode Flutter uses 64bit mode then the crash will happen.
Try to generate the APK and put it on the device manually
Also in your app Gradle exclude flutter 64bit .so

```
//#RFID
packagingOptions {
    exclude 'lib/arm64-v8a/libflutter.so'
    exclude 'lib/arm64-v8a/libapp.so'
   }
```

**Comment by bean5** [comment]
I am using the example code. Do I need to update the gradle file in the example?

**Comment by amorenew** [comment]
Yes, but I wonder do you have a native SDK for your ALPS device

**Comment by bean5** [comment]
How do I find what SDK the device uses?

**Comment by amorenew** [comment]
@bean5 From where you got that device? is it a Chinese company?
if they didn't give you native SDK for RFID ask them because it is custom hardware and maybe no RFID at all on your device.
Device info either use and app like system info or maybe in About page in settings

**Comment by bean5** [comment]
**About Device**
Model Number: ax6737_65_n
Android version: 7.0
Kernel version: 3.18.35
Custom build version: alps-mp-n0.mp1-V1.0.2_ax6737.65.n

**Comment by bean5** [comment]
I cannot install using VS Code. However, the following works:

```
flutter build apk
adb install -r build/app/outputs/apk/release/app-release.apk
```

**Comment by bean5** [comment]
It is from a Chinese company.

**Comment by amorenew** [comment]
@bean5 So is it working now or you don't have RFID cards?

**Comment by bean5** [comment]
I'm going to advise adding to README. Give me a moment to create a PR.

**Comment by bean5** [comment]
No, it does not work. The app builds and starts, but it will not read the RFID cards that I have. I think we can ticket that separately.
