### ISSUE TITLE
Merge https://github.com/amorenew/alps_rfid_ax6737 into this project?

### ISSUE THREAD

**Issue by bean5** [amorenew/alps_rfid_n6737#6]
It seems awkward to include packages like this:

`package:alps_rfid_n6737/alps_rfid_n6737.dart` or `package:alps_rfid_ax6737/alps_rfid_ax6737.dart`

It seems like maintaining both projects as 1 project would make more sense:

`package:alps_rfid/alps_rfid_n6737.dart` or `package:alps_rfid/alps_rfid_ax6737.dart`

**Comment by amorenew** [comment]
@bean5 Chinese made two different tablets and two different SDKs for our company
Check these folders in the two libraries
https://github.com/amorenew/alps_rfid_n6737/tree/master/android/src/main/jniLibs/armeabi-v7a
https://github.com/amorenew/alps_rfid_ax6737/tree/master/android/libs
